FROM apache/airflow:2.6.0

USER root

# Install wget to download Hive
RUN apt-get update && apt-get install -y wget

# Download and install Apache Hive 3.1.3
RUN wget https://archive.apache.org/dist/hive/hive-3.1.3/apache-hive-3.1.3-bin.tar.gz -O /tmp/hive.tar.gz && \
    tar -xzf /tmp/hive.tar.gz -C /opt/ && \
    mv /opt/apache-hive-3.1.3-bin /opt/hive && \
    rm /tmp/hive.tar.gz

# Set Hive environment variables
ENV HIVE_HOME=/opt/hive
ENV PATH=$PATH:$HIVE_HOME/bin

# Switch back to the airflow user
USER airflow