
version: '3'

services:
  atlas:
    image: sburn/apache-atlas:2.3.0
    container_name: atlas
    ports:
      - "21443:21443"
    environment:
      - ATLAS_ENABLE_TLS=true
      - ATLAS_KEYSTORE_PASSWORD=keystore_password
      - ATLAS_TRUSTSTORE_PASSWORD=truststore_password
    volumes:
      - ./atlas_security:/opt/atlas/conf/security
      - ./ssl:/opt/atlas/conf/ssl
      - ./atlas_data:/opt/apache-atlas/data
      - ./atlas_logs:/opt/apache-atlas/logs
    networks:
      - etl_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "--fail", "https://localhost:21443/api/atlas/admin/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  etl_network:
    external: true
